spring:
  application:
    name: IDENTITY-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
  instance:
#    prefer-ip-address: true
    hostname: localhost

server:
  port: 0

  eureka:
    instance:
      hostname: localhost



driverClassName: org.sqlite.JDBC
url: jdbc:sqlite:mydb.sqlite
username: sa
password: sa

